compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@chromatic-com/storybook@*":
    dependencies:
      react: 18.3.1
  "@storybook/addon-docs@*":
    dependencies:
      "@types/react": 18.3.17
  "@storybook/addon-onboarding@*":
    dependencies:
      react: 18.3.1
  "@storybook/react-vite@*":
    dependencies:
      typescript: 5.6.3
  eslint-plugin-storybook@*:
    dependencies:
      typescript: 5.6.3

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.6.0.cjs
